import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
const foods = [
  {
    key: 'egg',
    name: 'whole egg',
    displayName: 'Whole egg',
    category: 'protein',
    state: null,
    calories: 143,
    protein: 12.6,
    carbs: 0.7,
    fat: 9.5,
    fibre: 0,
    portion: { label: 'piece', amount: 1, unit: 'PIECE', grams: 50 },
    aliases: ['egg', 'eggs'],
  },
  {
    key: 'fried-egg',
    name: 'fried egg',
    displayName: 'Fried egg',
    category: 'protein',
    state: 'fried',
    calories: 196,
    protein: 13.6,
    carbs: 1.6,
    fat: 14.8,
    fibre: 0,
    portion: { label: 'piece', amount: 1, unit: 'PIECE', grams: 50 },
    aliases: ['fried eggs'],
  },
  {
    key: 'sourdough',
    name: 'sourdough bread',
    displayName: 'Sourdough bread',
    category: 'bread',
    state: null,
    calories: 289,
    protein: 11,
    carbs: 54,
    fat: 3.5,
    fibre: 2.7,
    portion: { label: 'slice', amount: 1, unit: 'SLICE', grams: 35 },
    aliases: ['bread'],
  },
  {
    key: 'feta',
    name: 'feta cheese',
    displayName: 'Feta cheese',
    category: 'dairy',
    state: null,
    calories: 264,
    protein: 14.2,
    carbs: 4.1,
    fat: 21.3,
    fibre: 0,
    portion: { label: 'serving', amount: 1, unit: 'SERVING', grams: 30 },
    aliases: ['feta'],
  },
  {
    key: 'cheddar',
    name: 'cheddar cheese',
    displayName: 'Cheddar cheese',
    category: 'dairy',
    state: null,
    calories: 403,
    protein: 24.9,
    carbs: 1.3,
    fat: 33.1,
    fibre: 0,
    portion: { label: 'slice', amount: 1, unit: 'SLICE', grams: 28 },
    aliases: ['cheddar'],
  },
  {
    key: 'almonds',
    name: 'almonds',
    displayName: 'Almonds',
    category: 'nuts',
    state: null,
    calories: 579,
    protein: 21.2,
    carbs: 21.6,
    fat: 49.9,
    fibre: 12.5,
    portion: { label: 'serving', amount: 1, unit: 'SERVING', grams: 28 },
    aliases: ['almond'],
  },
  {
    key: 'rice-cooked',
    name: 'white rice',
    displayName: 'Cooked white rice',
    category: 'grains',
    state: 'cooked',
    calories: 130,
    protein: 2.7,
    carbs: 28.2,
    fat: 0.3,
    fibre: 0.4,
    portion: { label: 'cup', amount: 1, unit: 'CUP', grams: 158 },
    aliases: ['cooked rice'],
  },
  {
    key: 'rice-dry',
    name: 'white rice',
    displayName: 'Dry white rice',
    category: 'grains',
    state: 'dry',
    calories: 365,
    protein: 7.1,
    carbs: 80,
    fat: 0.7,
    fibre: 1.3,
    portion: { label: 'cup', amount: 1, unit: 'CUP', grams: 185 },
    aliases: ['dry rice'],
  },
  {
    key: 'chicken-raw',
    name: 'chicken breast',
    displayName: 'Chicken breast raw',
    category: 'protein',
    state: 'raw',
    calories: 120,
    protein: 22.5,
    carbs: 0,
    fat: 2.6,
    fibre: 0,
    portion: { label: 'piece', amount: 1, unit: 'PIECE', grams: 150 },
    aliases: ['raw chicken breast'],
  },
  {
    key: 'chicken-grilled',
    name: 'chicken breast',
    displayName: 'Chicken breast grilled',
    category: 'protein',
    state: 'grilled',
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fibre: 0,
    portion: { label: 'piece', amount: 1, unit: 'PIECE', grams: 150 },
    aliases: ['grilled chicken breast'],
  },
  {
    key: 'oats',
    name: 'oats',
    displayName: 'Oats',
    category: 'grains',
    state: null,
    calories: 389,
    protein: 16.9,
    carbs: 66.3,
    fat: 6.9,
    fibre: 10.6,
    portion: { label: 'cup', amount: 1, unit: 'CUP', grams: 80 },
    aliases: ['oat'],
  },
  {
    key: 'yoghurt',
    name: 'plain yoghurt',
    displayName: 'Plain yoghurt',
    category: 'dairy',
    state: null,
    calories: 61,
    protein: 3.5,
    carbs: 4.7,
    fat: 3.3,
    fibre: 0,
    portion: { label: 'cup', amount: 1, unit: 'CUP', grams: 245 },
    aliases: ['yogurt', 'plain yogurt'],
  },
  {
    key: 'banana',
    name: 'banana',
    displayName: 'Banana',
    category: 'fruit',
    state: null,
    calories: 89,
    protein: 1.1,
    carbs: 22.8,
    fat: 0.3,
    fibre: 2.6,
    portion: { label: 'piece', amount: 1, unit: 'PIECE', grams: 118 },
    aliases: ['bananas'],
  },
];
async function seed(): Promise<void> {
  await prisma.user.upsert({
    where: { email: 'demo@example.com' },
    update: { displayName: 'Demo User' },
    create: {
      id: 'demo-user-id',
      email: 'demo@example.com',
      displayName: 'Demo User',
    },
  });
  for (const fixture of foods) {
    const food = await prisma.food.upsert({
      where: {
        provider_providerExternalId: {
          provider: 'SEED',
          providerExternalId: fixture.key,
        },
      },
      update: {
        displayName: fixture.displayName,
        rawProviderPayload: {
          source: 'documented demo fixture',
          fixture: fixture.key,
        },
      },
      create: {
        normalizedName: fixture.name,
        displayName: fixture.displayName,
        category: fixture.category,
        preparationState: fixture.state,
        provider: 'SEED',
        providerExternalId: fixture.key,
        caloriesPer100g: fixture.calories,
        proteinPer100g: fixture.protein,
        carbohydratesPer100g: fixture.carbs,
        fatPer100g: fixture.fat,
        fibrePer100g: fixture.fibre,
        rawProviderPayload: {
          source: 'documented demo fixture',
          fixture: fixture.key,
        },
        fetchedAt: new Date(),
      },
    });
    await prisma.foodPortion.upsert({
      where: { id: `seed-portion-${fixture.key}` },
      update: {
        label: fixture.portion.label,
        amount: fixture.portion.amount,
        unit: fixture.portion.unit,
        grams: fixture.portion.grams,
      },
      create: {
        id: `seed-portion-${fixture.key}`,
        foodId: food.id,
        label: fixture.portion.label,
        amount: fixture.portion.amount,
        unit: fixture.portion.unit,
        grams: fixture.portion.grams,
        source: 'SEED_FIXTURE',
      },
    });
    for (const alias of fixture.aliases)
      await prisma.foodAlias.upsert({
        where: { id: `seed-alias-${fixture.key}-${alias.replace(/\s/g, '-')}` },
        update: { alias, normalizedAlias: alias },
        create: {
          id: `seed-alias-${fixture.key}-${alias.replace(/\s/g, '-')}`,
          foodId: food.id,
          alias,
          normalizedAlias: alias,
        },
      });
  }
  const rules = [
    {
      id: 'seed-rule-some-cheese',
      quantifier: 'SOME',
      foodCategory: 'dairy',
      grams: 30,
    },
    {
      id: 'seed-rule-handful-nuts',
      quantifier: 'HANDFUL',
      foodCategory: 'nuts',
      grams: 30,
    },
    {
      id: 'seed-rule-slice-bread',
      quantifier: 'SLICE',
      foodCategory: 'bread',
      grams: 35,
    },
    {
      id: 'seed-rule-bowl-grains',
      quantifier: 'BOWL',
      foodCategory: 'grains',
      grams: 180,
    },
  ];
  for (const rule of rules)
    await prisma.portionRule.upsert({
      where: { id: rule.id },
      update: { grams: rule.grams },
      create: {
        ...rule,
        scope: 'SYSTEM',
        source: 'SEED_FIXTURE',
        confidence: 0.8,
        sampleCount: 0,
      },
    });
}
seed()
  .catch((error) => {
    process.stderr.write(
      `${error instanceof Error ? error.message : String(error)}\n`,
    );
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
